### ISSUE TITLE
Generating scripts?

### ISSUE THREAD

**Issue by psychemedia** [sparkd/mp-financial-interests#2]
Did you ever release the scripts used to generate this dataset?

**Comment by benscott** [comment]
Yes, I have just released the scripts: https://github.com/benscott/mp-financial-interests

**Comment by psychemedia** [comment]
@benscott Thanks - saw that; put my [quick hack to grab low hanging fruit](https://github.com/psychemedia/parlihacks/blob/master/notebooks/MP%20Register%20of%20Interests.ipynb) to shame!

A few things that occurred to me:

1. the tests you produced are really useful, and something I could add into my recipe (I'll do that when I get a chance). If we can get NGOs / third sector to give examples of register entries and  (structured) data they expect/ would like to get from such entries, that could then be coded up as tests that civic hackers could build scraping tools around. There are several benefits I can think of:
  - something to build the scraper towards
  - devs don't necessarily read things from a register that end users want to be able to work with, and/or lack subject matter expertise that helps them judge important or interesting features of the (ata in the) register;
  - helps devs understand needs of data/register users better;
  - devs may see structural things in the register that can be extracted that end users might not have realised was extractable.
2. Coming up with database schemas to represent data that can be extracted from registers, again based on needs of eg watchdog data users could be useful as a target for civic hackers.
3. If differently implemented scrapes of same data set to set schema exist, a recipe for comparing the scrapes / diffing them would be handy and would enable:
  - checking the performance of differently implemented scrapers
  - tracking improvements / helping bootstrap the development of a scraper
  - looking for differences in the data when running a single scraper repeatedly on a register that gets updated i.e. doing a diff on two full scrapes by the same scraper of the same db at different times. (I note this could also be done by logging db updates if the scraper is constructed to upsert scrape records on an existing db)
